name: HACS Action

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "1 1 1 * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"